Feature validate blocking schemas
data61/blocklib pull request #140
Opened 2021-03-10 11:20 UTC by hardbyte

Adds pydantic models for blocking schemas and carries out much stricter validation.

Closes #12
Closes #137

2021-03-15 01:22 UTC, wilko77 requested changes
`pydantic` looks really nice. 
Given that we define and validate user-provided configurations, what's best practice to provide documentation for the users? Is there some tooling we can use?

2021-03-15 01:22 UTC, wilko77 commented on blocklib/validation/__init__.py
> +    return BlockingSchemaModel.parse_obj(config)
why do you parse it twice?

2021-03-15 01:22 UTC, wilko77 commented on blocklib/validation/__init__.py
> +    # directly create a PSig or LambdaFold type
sounds like a good idea

2021-03-15 01:22 UTC, wilko77 commented on blocklib/validation/lambda_fold_validation.py
> +    #random_state: Optional[int] = Field(None, alias='random-state')
do we need this line?

2021-03-15 01:22 UTC, wilko77 commented on pyproject.toml
> +version = "0.1.8"
better: `0.1.8-dev`.

2021-03-15 01:48 UTC, hardbyte commented on blocklib/candidate_blocks_generator.py
> +    blocking_schema = validate_signature_config(signature_config)
Agree the names could be better. 

`generate_candidate_blocks` currently takes a Python dict version of the blocking schema - assumed to have been sourced from a JSON file. We validate that schema getting back a `BlockingSchemaModel` which is an instance of a Pydantic model, very similar to a dataclass.

`read_and_validate_blocking_schema` sounds like it reads a file to me, I'll rename to `validate_blocking_schema` for now.

I'll change the argument to `blocking_schema` instead of `signature_config`, and make it more explicit with `blocking_model` for the pydantic model.

I'd actually like to make `generate_candidate_blocks` take a `Union[BlockingSchemaModel, Dict]` - thoughts?

2021-03-15 01:53 UTC, hardbyte commented on blocklib/pprlindex.py
> +    def __init__(self, config: Union[PSigConfig, LambdaConfig]) -> None:
Done in 392df913c91f90669ed1e6ce6a2c7fab53dba465

2021-03-15 01:54 UTC, hardbyte commented on blocklib/pprlindex.py
> +        #logger.info('  Selected %d random reference values' % (len(ref_val_list)))
Aversion to printing in libraries, but laziness to import and setup logging... 

Luckily I believe you've added logging support since I rudely commented this out so I'll enable it

2021-03-15 01:57 UTC, hardbyte commented on blocklib/pprllambdafold.py
> +    def __init__(self, config: Union[LambdaConfig, Dict]):
That wouldn't be compatible with the old API so I'd suggest a deprecation period to continue accepting dict config for a version on two.

2021-03-15 02:00 UTC, hardbyte commented on blocklib/pprllambdafold.py
> +    def __init__(self, config: Union[LambdaConfig, Dict]):
The `parse_obj` is nice in that the errors are really on point.

```
from blocklib.validation import LambdaConfig
LambdaConfig.parse_obj({})
Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/blocklib-CJeb9hJb-py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a08a6d544657>", line 1, in <module>
    LambdaConfig.parse_obj({})
  File "pydantic/main.py", line 572, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 7 validation errors for LambdaConfig
blocking-features
  field required (type=value_error.missing)
Lambda
  field required (type=value_error.missing)
bf-len
  field required (type=value_error.missing)
num-hash-funcs
  field required (type=value_error.missing)
K
  field required (type=value_error.missing)
input-clks
  field required (type=value_error.missing)
random_state
  field required (type=value_error.missing)
```

Or closer:

```
LambdaConfig.parse_obj({'blocking-features': [], 'Lambda':2, 'bf-len': 'invalid', 'K': 2, 'input-clks': False, 'random_state': 0, 'num-hash-funcs': 20})
Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/blocklib-CJeb9hJb-py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-9dd1572df494>", line 1, in <module>
    LambdaConfig.parse_obj({'blocking-features': [], 'Lambda':2, 'bf-len': 'invalid', 'K': 2, 'input-clks': False, 'random_state': 0, 'num-hash-funcs': 20})
  File "pydantic/main.py", line 572, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LambdaConfig
bf-len
  value is not a valid integer (type=type_error.integer)
```

2021-03-15 02:03 UTC, hardbyte commented on blocklib/validation/__init__.py
> +    # directly create a PSig or LambdaFold type
We do this inside `BlockingSchemaModel.config_gen`, as in the `BlockingSchemaModel` will have a `config` attribute that is either the `PSigConfig` or `LambdaConfig`.

2021-03-15 02:13 UTC, hardbyte commented on blocklib/validation/__init__.py
> +    return BlockingSchemaModel.parse_obj(config)
Good question, I thought it was justified but on investigation I no longer think it is.

My logic was something like this:

The first one is using a `BlockingSchemaBaseModel` which applies the same level of validation that was already in the library (does it contain the expected top level keys) giving a decent error if the version is missing or if the type is unsupported by this version of `blocklib`: 

```
BlockingSchemaBaseModel.parse_obj({'version': 1, 'config': {}, 'type': 'PSIG'})
Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/blocklib-CJeb9hJb-py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-e40ecbadccd2>", line 1, in <module>
    BlockingSchemaBaseModel.parse_obj({'version': 1, 'config': {}, 'type': 'PSIG'})
  File "pydantic/main.py", line 572, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BlockingSchemaBaseModel
type
  value is not a valid enumeration member; permitted: 'p-sig', 'lambda-fold' (type=type_error.enum; enum_values=[<BlockingSchemaTypes.psig: 'p-sig'>, <BlockingSchemaTypes.lambdafold: 'lambda-fold'>])
```

I had thought that the `BlockingSchemaModel` gave lots of validation errors that might be confusing if the top level was wrong, I think behaviour has improved with the config_gen "hack". The current output from validating a poorly configured blocking_schema with the full pydantic model indeed seems acceptable:

```
BlockingSchemaModel.parse_obj({'version': 1, 'config': {}, 'type': 'PSIG'})
Traceback (most recent call last):
  File "/home/brian/.cache/pypoetry/virtualenvs/blocklib-CJeb9hJb-py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-036a72b586b9>", line 1, in <module>
    BlockingSchemaModel.parse_obj({'version': 1, 'config': {}, 'type': 'PSIG'})
  File "pydantic/main.py", line 572, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for BlockingSchemaModel
type
  value is not a valid enumeration member; permitted: 'p-sig', 'lambda-fold' (type=type_error.enum; enum_values=[<BlockingSchemaTypes.psig: 'p-sig'>, <BlockingSchemaTypes.lambdafold: 'lambda-fold'>])
config
  Unsupported blocking type (type=value_error)
```

So there are two errors where one would be sufficient, but I'll go ahead and remove the base model.

2021-03-15 02:20 UTC, hardbyte commented on blocklib/validation/__init__.py
> +    return BlockingSchemaModel.parse_obj(config)
Done in b3653861c6286bdf4944ceb6931777ffd70ab161

2021-03-15 02:27 UTC, hardbyte commented on blocklib/validation/lambda_fold_validation.py
> +    #random_state: Optional[int] = Field(None, alias='random-state')
Let's just say the blocking schema isn't the most consistent schema I've ever come across. I had this to map the hypenated `random-state` to the more Python friendly underscore separated `random_state` but it turns out the schema mixed and matched:

![image](https://user-images.githubusercontent.com/855189/111095553-8a837800-85a2-11eb-98a1-c237ac0fbdfa.png)

I'm happy to include it (or change them all to use underscores), but note it would be a breaking change. So thought I'd just leave it for now, I'll open an issue - https://github.com/data61/blocklib/issues/142

2021-03-15 02:28 UTC, hardbyte commented on blocklib/validation/lambda_fold_validation.py
> +    #random_state: Optional[int] = Field(None, alias='random-state')
Cough `signatureSpecs` camelCase is in there too

2021-03-15 02:29 UTC, hardbyte commented on pyproject.toml
> +version = "0.1.8"
Done in 569a320f0630f8e1d69ce221c5f813c82e48d24b

2021-03-15 02:38 UTC, hardbyte commented
> Given that we define and validate user-provided configurations, what's best practice to provide documentation for the users? Is there some tooling we can use?

Yeah the _tour de force_ of pydantic was supposed to me proudly showing that `PSigConfig.schema_json()` or even `BlockingSchemaModel.schema_json()` would produce fully valid json schemas 🥳. Unfortunately there is something not working with the mix of `Literal` and `Enum` types so that doesn't work right now. 👎🏼 
I suspect that there will be a minor refactoring required after Pydantic officially supports discriminated union types, and then we will get full json schema support. The library can then expose that as documentation.

2021-03-16 00:17 UTC, wilko77 commented on blocklib/candidate_blocks_generator.py
> +    blocking_schema = validate_signature_config(signature_config)
I find it a bit smelly to use the `Union[BlockingSchemaModel, Dict]` as an argument for `generate_candidate_blocks`. Instead, I would only accept `BlockingSchemaModel` and make sure that `BlockingSchemaModel` has appropriate helper functions to read the model from `Dict`. 
In fact, I would make all the internal functions only accept the pydantic models. If I am not mistaken, then pydantic offers helper functions to generate models from dicts/json. 
It comes down to a separation of concerns thing.
Yes, that breaks the current api a little, but we would end up with something a lot cleaner.

2021-03-16 00:19 UTC, wilko77 commented on blocklib/pprllambdafold.py
> +    def __init__(self, config: Union[LambdaConfig, Dict]):
Is anyone actually using this outside of blocklib? Let's make a version 1.*.* and break things. Viva la revolution!

2021-03-16 00:28 UTC, hardbyte commented on blocklib/candidate_blocks_generator.py
> +    blocking_schema = validate_signature_config(signature_config)
> In fact, I would make all the internal functions only accept the pydantic models. 

I'd be very much in favor of that. But surely `generate_candidate_blocks` isn't an **internal** function? Anonlink client [uses it directly for example](https://github.com/data61/anonlink-client/blob/e8c541a61a9c2164f5862d021b2f6522921e0e2b/anonlinkclient/utils.py#L88).
Happy to implement what ever you want here though, break the external api and force `blocklib` users to pass blocklib's pydantic models for configuration? Please confirm before I do that.

> If I am not mistaken, then pydantic offers helper functions to generate models from dicts/json.
Yes, of course: `Model.parse_obj(dictionary_data)`

2021-03-16 00:29 UTC, wilko77 commented on blocklib/validation/lambda_fold_validation.py
> +    #random_state: Optional[int] = Field(None, alias='random-state')
we are not the only ones [mixing the styles](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html#aws-ip-syntax)... 
We should avoid kebab-case though, as it cannot be accessed easily by JavaScript. 
I guess we should defined a new version of the schema that unifies the formatting. There is also a mix of upper and lower case. 
If I read that correctly, then pydantic would let us build in backwards compatibility with the `alias` thingy? Sweet.

2021-03-16 00:31 UTC, hardbyte commented on blocklib/candidate_blocks_generator.py
> +    blocking_schema = validate_signature_config(signature_config)
What if we outsourced the magic conversion to https://pydantic-docs.helpmanual.io/usage/validation_decorator/

That (provisional api) looks like it might validate and convert for us.

2021-03-16 02:17 UTC, wilko77 commented on blocklib/candidate_blocks_generator.py
> +    blocking_schema = validate_signature_config(signature_config)
I don't know, the magic converter looks nice, but, it's still beta and also feels a bit like a hack. 
For the `generate_candidate_blocks` and anonlink-client. You can see that it loads the config first from json, then does some acrobatics to extract a config value, loads the whole dataset into memory, and then calls blocklib. If it would have properly parsed the config, then the access would have been cleaner and it would fail early if the config is wrong.

I'm still leaning towards only allowing the pydantic models, however, before we make braking changes, we should review the whole code base and make it consistent. This seems more like a version 1.0 kind of activity. :) Thus for now, do your non-breaking change.

2021-03-16 02:28 UTC, wilko77 approved these changes
Please check the test coverage.

2021-03-16 02:28 UTC, wilko77 commented on blocklib/candidate_blocks_generator.py
>          ``docs/schema/signature-config-schema.json``
that's not a valid link.

2021-03-18 04:37 UTC, hardbyte commented on blocklib/candidate_blocks_generator.py
>          ``docs/schema/signature-config-schema.json``
Turns out the docstrings are not rendered anywhere in sphinx... I'll put together a very basic python api page for now.

2021-03-18 06:10 UTC, merged